# -*- coding: utf-8 -*-
"""Gen.ai-APIs key.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IcUmogE1j2lm0xOlreaHAr33MZA2q50-
"""

from openai import OpenAI

from google.colab import userdata
client = OpenAI(
    api_key=userdata.get('GROQ_API_KEYS'),
    base_url="https://api.groq.com/openai/v1",
)

response = client.responses.create(
    input="Explain the importance of fast language models",
    model="openai/gpt-oss-20b",
)
print(response.output_text)